# -*- coding: utf-8 -*-
"""GroceryStoreManagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLG4iIq62F33UlkYNtcWKgTiGZpupR3_
"""

#Grocery Store Management


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the CSV file into a DataFrame
df = pd.read_csv("Groceries_dataset.csv")

# Continue with the rest of the analysis...
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Extract month, year, and day of week from the 'Date' column
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df['DayOfWeek'] = df['Date'].dt.dayofweek

# Basic data analysis
# Number of unique members
num_members = df['Member_number'].nunique()

# Number of unique items
num_items = df['itemDescription'].nunique()

# Total number of transactions
total_transactions = len(df)

# Average number of transactions per member
avg_transactions_per_member = total_transactions / num_members

# Monthly sales trends
monthly_sales = df.groupby(['Year', 'Month']).size().reset_index(name='Transactions')

# Most popular items
popular_items = df['itemDescription'].value_counts().head(10)

# Day of week with the most transactions
day_with_most_transactions = df['DayOfWeek'].value_counts().idxmax()

# Visualizations
# Monthly sales trends
plt.figure(figsize=(12, 6))
sns.lineplot(x='Month', y='Transactions', hue='Year', data=monthly_sales)
plt.title('Monthly Sales Trends')
plt.xlabel('Month')
plt.ylabel('Number of Transactions')
plt.xticks(range(1, 13))
plt.legend(title='Year')
plt.show()

# Most popular items
plt.figure(figsize=(10, 6))
sns.barplot(x=popular_items.values, y=popular_items.index, palette='viridis')
plt.title('Top 10 Most Popular Items')
plt.xlabel('Frequency')
plt.ylabel('Item Description')
plt.show()

# Day of week with the most transactions
day_labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
plt.figure(figsize=(8, 5))
sns.countplot(x='DayOfWeek', data=df, order=df['DayOfWeek'].value_counts().index, palette='Set2')
plt.title('Transactions by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Number of Transactions')
plt.xticks(range(7), day_labels)
plt.annotate(f'Most transactions: {day_labels[day_with_most_transactions]}',
             xy=(day_with_most_transactions, df['DayOfWeek'].value_counts().max()),
             xytext=(3, 50),
             textcoords='offset points',
             arrowprops=dict(arrowstyle='->', color='red'))
plt.show()

